jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: mysql://bdfb068b0816f8:b3b14f5e@eu-cluster-west-01.k8s.cleardb.net/heroku_166b63083c3c2df?reconnect=true
    #url: jdbc:mysql://localhost:3306/supportportal?serverTimezone=Europe/Paris
    password: b3b14f5e
    username: bdfb068b0816f8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false